# Generated by Django 5.2.8 on 2025-11-18 03:27

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryTerm",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "delivery_term",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMode",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment_mode",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment_term",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("buyer_first_name", models.CharField(max_length=100)),
                ("buyer_last_name", models.CharField(max_length=100)),
                ("buyer_email", models.EmailField(max_length=254)),
                ("buyer_phone", models.CharField(blank=True, max_length=50, null=True)),
                ("buyer_company_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("no_lead", "No Lead"),
                            ("new", "New"),
                            ("converted", "Converted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("forwarded", "Forwarded"),
                            ("sent_to_distributor", "Sent to Distributor"),
                            ("accepted_by_distributor", "Accepted by Distributor"),
                            ("rejected_by_distributor", "Rejected by Distributor"),
                        ],
                        default="no_lead",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("source", models.CharField(default="web", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_leads",
                        to="commerce.lead",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="leads", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "lead",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceTier",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "minimum_uom_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "price_per_uom",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("valid_from_date", models.DateTimeField(blank=True, null=True)),
                ("valid_to_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_tiers_buyer",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "delivery_term",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="commerce.deliveryterm"
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_tiers",
                        to="tenants.tenantaddress",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="commerce.paymentterm"
                    ),
                ),
                (
                    "product_sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_tiers",
                        to="products.productsku",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_tiers_seller",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "price_tier",
                "ordering": ["seller", "buyer", "minimum_uom_quantity"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("no_order", "No Order"),
                            ("new", "New"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("invoiced", "Invoiced"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("payment_received", "Payment Received"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("declined", "Declined"),
                            ("back_ordered", "Back Ordered"),
                        ],
                        default="no_order",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders_buyer",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "delivery_term",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="commerce.deliveryterm"),
                ),
                (
                    "payment_mode",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="commerce.paymentmode"),
                ),
                (
                    "payment_term",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="commerce.paymentterm"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders_seller",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="tenants.tenantaddress",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderDetail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "no_of_units",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="commerce.purchaseorder"
                    ),
                ),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.product")),
                ("sku", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.productsku")),
            ],
            options={
                "db_table": "purchase_order_detail",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("no_request", "No Request"),
                            ("new", "New"),
                            ("requested", "Requested"),
                            ("responded", "Responded"),
                            ("accepted", "Accepted"),
                            ("cancelled", "Cancelled"),
                            ("declined", "Declined"),
                            ("pending", "Pending"),
                            ("pending_activation", "Pending Activation"),
                        ],
                        default="no_request",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_requests_buyer",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "delivery_term",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="commerce.deliveryterm"),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_requests",
                        to="commerce.lead",
                    ),
                ),
                (
                    "payment_mode",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="commerce.paymentmode"),
                ),
                (
                    "payment_term",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="commerce.paymentterm"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_requests_seller",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_requests",
                        to="tenants.tenantaddress",
                    ),
                ),
            ],
            options={
                "db_table": "quote_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="quote_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_order",
                to="commerce.quoterequest",
            ),
        ),
        migrations.CreateModel(
            name="QuoteRequestDetail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "no_of_units",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.product")),
                (
                    "quote_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="commerce.quoterequest"
                    ),
                ),
                (
                    "requested_sku",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_quote_details",
                        to="products.productsku",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="products.productsku"
                    ),
                ),
            ],
            options={
                "db_table": "quote_request_detail",
                "ordering": ["quote_request", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentAdvice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("estimated_time_of_dispatch", models.DateTimeField(blank=True, null=True)),
                ("estimated_time_of_arrival", models.DateTimeField(blank=True, null=True)),
                ("carrier", models.CharField(blank=True, max_length=100, null=True)),
                ("carrier_number", models.CharField(blank=True, max_length=100, null=True)),
                ("vessel_name", models.CharField(blank=True, max_length=100, null=True)),
                ("port_of_loading", models.CharField(blank=True, max_length=100, null=True)),
                ("port_of_discharge", models.CharField(blank=True, max_length=100, null=True)),
                ("additional_comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="commerce.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "shipment_advice",
                "ordering": ["-created_at"],
            },
        ),
    ]
