# Generated by Django 5.2.8 on 2025-11-18 23:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_cart_cartitem"),
        ("products", "0001_initial"),
        ("tenants", "0002_marketplaceconfig_sellermarketplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectCheckout",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                            ("cash_on_delivery", "Cash on Delivery"),
                            ("net_terms", "Net Terms"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("shipping_cost", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "direct_checkout",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_placed", "Order Placed"),
                            ("order_accepted", "Order Accepted"),
                            ("order_shipped", "Order Shipped"),
                            ("order_delivered", "Order Delivered"),
                            ("payment_received", "Payment Received"),
                            ("review_posted", "Review Posted"),
                            ("product_back_in_stock", "Product Back in Stock"),
                            ("price_drop", "Price Drop"),
                            ("new_message", "New Message"),
                            ("quote_received", "Quote Received"),
                            ("quote_accepted", "Quote Accepted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, help_text="Link to related resource", max_length=500, null=True)),
                ("data", models.JSONField(blank=True, default=dict, help_text="Additional notification data")),
                ("is_read", models.BooleanField(default=False)),
                ("is_email_sent", models.BooleanField(default=False)),
                ("is_sms_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                            ("cash_on_delivery", "Cash on Delivery"),
                            ("net_terms", "Net Terms"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, help_text="External payment gateway ID", max_length=255, null=True),
                ),
                (
                    "payment_gateway",
                    models.CharField(blank=True, help_text="Stripe, PayPal, etc", max_length=50, null=True),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict, help_text="Payment gateway response")),
                ("notes", models.TextField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductView",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "session_id",
                    models.CharField(blank=True, help_text="Anonymous session ID", max_length=255, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("referrer", models.CharField(blank=True, max_length=500, null=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product_view",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed", "Fixed Amount")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount amount for percentage discounts",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "usage_limit",
                    models.IntegerField(blank=True, help_text="Total usage limit (null = unlimited)", null=True),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("per_user_limit", models.IntegerField(blank=True, help_text="Per-user usage limit", null=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "promo_code",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("query", models.CharField(max_length=255)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("results_count", models.IntegerField(default=0)),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "search_query",
                "ordering": ["-searched_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="cart_item_cart_id_product_id",
        ),
        migrations.RenameIndex(
            model_name="cart",
            new_name="cart_session_c72894_idx",
            old_name="cart_session_active_idx",
        ),
        migrations.RenameIndex(
            model_name="cart",
            new_name="cart_buyer_i_cbfd28_idx",
            old_name="cart_buyer_active_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="customer_email_c21aac_idx",
            old_name="customer_email_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="customer_tenant__e23123_idx",
            old_name="customer_tenant_email_idx",
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
        migrations.AddField(
            model_name="directcheckout",
            name="billing_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_checkouts",
                to="tenants.tenantaddress",
            ),
        ),
        migrations.AddField(
            model_name="directcheckout",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="checkouts", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="directcheckout",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="checkouts", to="commerce.cart"
            ),
        ),
        migrations.AddField(
            model_name="directcheckout",
            name="delivery_term",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="commerce.deliveryterm"),
        ),
        migrations.AddField(
            model_name="directcheckout",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_checkouts",
                to="commerce.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="directcheckout",
            name="payment_term",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="commerce.paymentterm"
            ),
        ),
        migrations.AddField(
            model_name="directcheckout",
            name="shipping_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_checkouts",
                to="tenants.tenantaddress",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="commerce.purchaseorder"
            ),
        ),
        migrations.AddField(
            model_name="productview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="product_views", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="productview",
            name="viewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_views",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="searcher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_queries",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="directcheckout",
            index=models.Index(fields=["buyer", "is_completed"], name="direct_chec_buyer_i_2ec707_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "is_read"], name="notificatio_recipie_201701_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["created_at"], name="notificatio_created_db7ad3_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["order", "status"], name="payment_order_i_c618ed_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["transaction_id"], name="payment_transac_9ff03c_idx"),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(fields=["product", "viewed_at"], name="product_vie_product_287761_idx"),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(fields=["viewer"], name="product_vie_viewer__bd5928_idx"),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(fields=["query"], name="search_quer_query_d119bd_idx"),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(fields=["searched_at"], name="search_quer_searche_11aa3f_idx"),
        ),
    ]
