# Generated by Django 5.2.8 on 2025-11-18 22:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(default="Main Marketplace", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("b2b_negotiation", "B2B Negotiation (Lead → Quote → Order)"),
                            ("direct_marketplace", "Direct Marketplace (Cart → Order)"),
                            ("hybrid", "Hybrid (Both B2B and Direct)"),
                            ("multi_vendor", "Multi-Vendor Marketplace"),
                        ],
                        default="b2b_negotiation",
                        help_text="Primary marketplace operation mode",
                        max_length=50,
                    ),
                ),
                (
                    "enable_shopping_cart",
                    models.BooleanField(default=True, help_text="Enable shopping cart functionality"),
                ),
                (
                    "enable_guest_checkout",
                    models.BooleanField(default=False, help_text="Allow guests to checkout without registration"),
                ),
                ("enable_wishlist", models.BooleanField(default=False, help_text="Enable product wishlist feature")),
                (
                    "enable_lead_generation",
                    models.BooleanField(default=True, help_text="Enable lead generation workflow"),
                ),
                (
                    "enable_quote_negotiation",
                    models.BooleanField(default=True, help_text="Enable quote request and negotiation"),
                ),
                (
                    "require_quote_approval",
                    models.BooleanField(default=True, help_text="Require seller approval for quotes"),
                ),
                (
                    "enable_distributor_network",
                    models.BooleanField(default=True, help_text="Enable distributor forwarding and network"),
                ),
                (
                    "enable_direct_purchase",
                    models.BooleanField(default=False, help_text="Allow direct purchase without negotiation"),
                ),
                ("enable_instant_checkout", models.BooleanField(default=False, help_text="Enable one-click checkout")),
                (
                    "skip_quote_for_direct",
                    models.BooleanField(default=False, help_text="Skip quote step for direct purchases"),
                ),
                (
                    "enable_multiple_sellers",
                    models.BooleanField(default=True, help_text="Allow multiple sellers on platform"),
                ),
                (
                    "enable_seller_storefronts",
                    models.BooleanField(default=False, help_text="Enable individual seller storefronts"),
                ),
                (
                    "allow_cross_seller_cart",
                    models.BooleanField(default=False, help_text="Allow items from multiple sellers in one cart"),
                ),
                (
                    "enable_dynamic_pricing",
                    models.BooleanField(default=True, help_text="Enable dynamic pricing and price tiers"),
                ),
                (
                    "enable_volume_discounts",
                    models.BooleanField(default=True, help_text="Enable volume-based discounts"),
                ),
                (
                    "show_prices_to_guests",
                    models.BooleanField(default=False, help_text="Show prices to non-authenticated users"),
                ),
                (
                    "enable_promotional_pricing",
                    models.BooleanField(default=False, help_text="Enable promotional/sale pricing"),
                ),
                (
                    "enable_customer_accounts",
                    models.BooleanField(default=True, help_text="Enable customer account creation from leads"),
                ),
                (
                    "enable_customer_portal",
                    models.BooleanField(default=False, help_text="Enable customer self-service portal"),
                ),
                (
                    "enable_saved_addresses",
                    models.BooleanField(default=True, help_text="Allow customers to save multiple addresses"),
                ),
                (
                    "enable_online_payment",
                    models.BooleanField(default=False, help_text="Enable online payment processing"),
                ),
                (
                    "enable_credit_terms",
                    models.BooleanField(default=True, help_text="Enable credit terms and net payment"),
                ),
                (
                    "enable_partial_payments",
                    models.BooleanField(default=False, help_text="Allow partial/installment payments"),
                ),
                (
                    "enable_product_reviews",
                    models.BooleanField(default=False, help_text="Enable product reviews and ratings"),
                ),
                ("enable_seller_ratings", models.BooleanField(default=False, help_text="Enable seller ratings")),
                (
                    "require_verified_purchase",
                    models.BooleanField(default=True, help_text="Require verified purchase for reviews"),
                ),
                (
                    "auto_approve_quotes",
                    models.BooleanField(default=False, help_text="Automatically approve quotes without seller action"),
                ),
                (
                    "auto_create_customer",
                    models.BooleanField(default=True, help_text="Automatically create customer from first order"),
                ),
                ("send_notifications", models.BooleanField(default=True, help_text="Send email/SMS notifications")),
                (
                    "min_order_value",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Minimum order value (0 = no minimum)", max_digits=10
                    ),
                ),
                ("max_cart_items", models.IntegerField(default=100, help_text="Maximum items allowed in cart")),
                (
                    "session_timeout_minutes",
                    models.IntegerField(default=30, help_text="Shopping session timeout in minutes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marketplace Configuration",
                "verbose_name_plural": "Marketplace Configurations",
                "db_table": "marketplace_config",
            },
        ),
        migrations.CreateModel(
            name="SellerMarketplace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("storefront_name", models.CharField(max_length=255)),
                ("storefront_slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allow_direct_purchase",
                    models.BooleanField(
                        blank=True, default=None, help_text="Override global direct purchase setting", null=True
                    ),
                ),
                (
                    "require_quote_approval",
                    models.BooleanField(
                        blank=True, default=None, help_text="Override global quote approval requirement", null=True
                    ),
                ),
                (
                    "min_order_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Seller-specific minimum order value",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("auto_accept_orders", models.BooleanField(default=False)),
                ("allow_negotiations", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.OneToOneField(
                        limit_choices_to={"type": "seller"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller Marketplace",
                "verbose_name_plural": "Seller Marketplaces",
                "db_table": "seller_marketplace",
            },
        ),
    ]
