# Generated by Django 5.2.8 on 2025-11-18 23:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0003_directcheckout_notification_payment_productview_and_more"),
        ("products", "0001_initial"),
        ("tenants", "0002_marketplaceconfig_sellermarketplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product_attribute",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Variant name (e.g., Red - Large)", max_length=255)),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Price adjustment from base price (+ or -)",
                        max_digits=10,
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "product_variant",
                "ordering": ["product", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariantAttribute",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "product_variant_attribute",
            },
        ),
        migrations.CreateModel(
            name="SellerRating",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "shipping_speed_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "product_quality_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review", models.TextField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "seller_rating",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(default="My Wishlist", max_length=255)),
                ("is_public", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wishlist",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "wishlist_item",
                "ordering": ["-added_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False, help_text="Feature this product on homepage"),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.CharField(blank=True, help_text="Brief product summary", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(blank=True, default=dict, help_text="Product specifications in JSON format"),
        ),
        migrations.AddField(
            model_name="product",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "quantity_available",
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    "quantity_reserved",
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    "quantity_incoming",
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    "reorder_level",
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    "reorder_quantity",
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                ("last_restocked_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="inventory", to="products.product"
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="inventory", to="products.productsku"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="tenants.tenantaddress",
                    ),
                ),
            ],
            options={
                "db_table": "inventory",
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="products.productattribute",
                    ),
                ),
            ],
            options={
                "db_table": "product_attribute_value",
                "ordering": ["attribute", "value"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.URLField(blank=True, help_text="Category image URL", null=True)),
                ("icon", models.CharField(blank=True, help_text="Icon class or name", max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
                "db_table": "product_category",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.productcategory",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("image_url", models.URLField(help_text="Image URL (can be CDN, S3, etc)")),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="products.product"
                    ),
                ),
            ],
            options={
                "db_table": "product_image",
                "ordering": ["-is_primary", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("review", models.TextField()),
                ("is_verified_purchase", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("helpful_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="product_reviews", to="tenants.tenant"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verified purchase order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="commerce.purchaseorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="products.product"
                    ),
                ),
            ],
            options={
                "db_table": "product_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="products", to="products.producttag"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="product_slug_b8980b_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["seller", "is_active"], name="product_seller__6aac89_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category", "is_active"], name="product_categor_71bada_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_featured", "is_active"], name="product_is_feat_1b9f5c_idx"),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="products.productsku"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="productvariantattribute",
            name="attribute_value",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.productattributevalue"),
        ),
        migrations.AddField(
            model_name="productvariantattribute",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_values",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="sellerrating",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="given_seller_ratings", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="sellerrating",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Related order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="commerce.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="sellerrating",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="seller_ratings", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="wishlists", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product"),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="variant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="products.productvariant"
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="wishlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="items", to="products.wishlist"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productattributevalue",
            unique_together={("attribute", "value")},
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(fields=["slug"], name="product_cat_slug_93e2a7_idx"),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(fields=["parent"], name="product_cat_parent__b54811_idx"),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(fields=["is_active"], name="product_cat_is_acti_ede319_idx"),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["product", "is_primary"], name="product_ima_product_4c0682_idx"),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(fields=["product", "is_approved"], name="product_rev_product_861d88_idx"),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(fields=["buyer"], name="product_rev_buyer_i_352f5e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "buyer", "order")},
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["product", "warehouse"], name="inventory_product_5c401c_idx"),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["sku", "warehouse"], name="inventory_sku_id_5d2762_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("product", "sku", "variant", "warehouse")},
        ),
        migrations.AlterUniqueTogether(
            name="productvariantattribute",
            unique_together={("variant", "attribute_value")},
        ),
        migrations.AddIndex(
            model_name="sellerrating",
            index=models.Index(fields=["seller", "is_approved"], name="seller_rati_seller__cd703b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="sellerrating",
            unique_together={("seller", "buyer", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("wishlist", "product", "variant")},
        ),
    ]
